### ISSUE TITLE
Inconsistent with familiar user experience

### ISSUE THREAD

**Issue by emouawad** [lojals/JOEmojiableBtn#3]
Of course this is a familiar user experience on Facebook:
While the difference is small - it is important
in this control user has to:
- click once to activate view
- click a second time to pick emoji
  While on FB user (long presses) once and immediately the toolbar is activated and shown 
  I believe as an alternative implementation a long press event is more familiar.

**Comment by lojals** [comment]
This control is actually using one tap por single action as Facebook like, and Long Tap to open the Reactions bar. Facebook just have those events not two clicks as you mentioned. The real issue is that in my version the user doesn't have control automatically from the Touch Begin Method, because is a different view.

**Comment by emouawad** [comment]
I believe you misunderstood what i was trying to describe.
I was trying to describe exactly the related open issue titled "selectedOption never get called #4"
Apparently it's a popular request ;)
